### ISSUE TITLE
[Feature] Emissive map

### ISSUE THREAD

**Issue by StjerneIdioten** [StjerneIdioten/I3D-Blender-Addon#133]
Export emissive maps connected to bsdf node under the tag `<Emissivemap fileId="0"/>` in its respective material.

**Comment by Kieruss** [comment]
It'd be great if it could export just a colour too via
![image](https://user-images.githubusercontent.com/24835155/153444999-4512897d-0874-462e-bc7b-f6d0e02eaace.png)
or
![image](https://user-images.githubusercontent.com/24835155/153445176-efe8b2f7-815f-4763-beb1-a95831c46ac1.png)
Which would then add the emissiveColor attribute, like below
`<Material name="lightBeam_mat" materialId="123" emissiveColor="1 1 1 1" customShaderId="1">`
