### ISSUE TITLE
[Bug Report] Light panel doesn't work (2.93)

### ISSUE THREAD

**Issue by NMC-TBone** [StjerneIdioten/I3D-Blender-Addon#137]
## Describe the bug
I3D Light Attributes drop down menu doesn't work in Blender 2.93

## Log file
Python: Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\i3dio\ui\light.py", line 339, in draw
    i3d_property(layout, obj.i3d_attributes, 'type_of_light', obj)
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\i3dio\ui\helper_functions.py", line 66, in i3d_property
    lab.label(text=attributes.__annotations__[attribute][1]['name'])
TypeError: '_PropertyDeferred' object is not subscriptable

location: <unknown location>:-1

## Screenshots
![image](https://user-images.githubusercontent.com/57712777/122656301-89da1f00-d159-11eb-9755-c963584f59e8.png)

**Comment by StjerneIdioten** [comment]
> I'm not going to do a pull request, because I know you have much bigger work going on, and I did at best a cursory look - this gets the panel to function again, I have no idea what else, if anything it breaks.

It probably doesn't break anything. Light panels are the only UI element using that "test" code for a new way to get GE specific dependencies into the UI. Blender's usage of annotations is already "hacky" and my creative solution to abuse it even more was bound to break at some point 🤣 

If I have the time I will look into adding it as a bugfix, I still do those even while I am "working on bigger things" 😉
