### ISSUE TITLE
[Bug Report]Some of the faces are exported 'inside out'

### ISSUE THREAD

**Issue by XPModder** [StjerneIdioten/I3D-Blender-Addon#138]
When exporting a slightly complex model, some of the faces end up facing the wrong way. So the inside is textured and visible and the outside is 'invisible'. This somehow only applies to some of the faces while others (even of the same object) are correct.
Not sure how else to explain this...
This is how it looks in Giants Editor and ingame. The missing faces are there, they are just invisible from the outside. If the camera were inside the beam you would be able to see all of the faces. The second image shows the same part from a different angle.
![grafik](https://user-images.githubusercontent.com/30577392/123430344-5c153000-d5c8-11eb-96dd-2ef5a8473e8b.png)
![grafik](https://user-images.githubusercontent.com/30577392/123430572-a3032580-d5c8-11eb-9d75-ab51e9b5651e.png)

Here is the same part in blender:
![grafik](https://user-images.githubusercontent.com/30577392/123431015-1ad15000-d5c9-11eb-940c-2beaea050a9e.png)
Here the faces are all visible from the outside

The export log does not show any errors. But I attached it anyways.
[ASA-Lift WR 365-2 - Kopie_export_log.txt](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/6716429/ASA-Lift.WR.365-2.-.Kopie_export_log.txt)

I am using Blender 2.90.1 if thats important.

**Comment by kbrandwijk** [comment]
Could you make sure and check the face orientation in Blender? By default, it doesn't do backface culling in that viewport mode, you wouldn't notice them being inside out.

**Comment by XPModder** [comment]
Oh. 
I pretty new to blender. I didn't know blender had face orientation since in blender they are all visible from both sides.
I checked and for some reason, some of the faces were the wrong way around in blender, so I fixed that.
Now everything is exported correctly.

Thanks for the help!
