### ISSUE TITLE
Scaled objects have disappearing faces in GE

### ISSUE THREAD

**Issue by sistem442** [StjerneIdioten/I3D-Blender-Addon#141]
Hello,
I am kind of new to modding, so maybe I am just doing something wrong. I have blender 2.92 and 4.0 version of exporter. I have installed exporter by instructions.

When I export scaled object to GE some faces are disappearing as I rotate or move the camera arround the object. If object is unscaled all is looking correctly in GE. Before exporting I did use apply all tranformations in Blender.

[LS19-20211002T073308Z-001.zip](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/7271048/LS19-20211002T073308Z-001.zip)

With best regards
Boris

**Comment by ssnd292** [comment]
Can you please upload the i3d?

**Comment by sistem442** [comment]
Yes. Thank you for quick reply :)
[CP 200P.zip](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/7271388/CP.200P.zip)

**Comment by ssnd292** [comment]
![2021-10-02 14_29_23-Blender_  C__Users_ssnd2_Downloads_LS19-20211002T073308Z-001_LS19_CP 200P blend](https://user-images.githubusercontent.com/3914410/135716116-52ed198a-d4ad-41db-957b-269a18fbdf18.jpg)
You have several objects with inverted normals. 

CTRL N to fix this. This is nothing to do with the exporter, so it should be closed as invalid.

**Comment by sistem442** [comment]
Thank you very much ssnd292, fliping the normals solved the issue.
