### ISSUE TITLE
Import i3D for settings only

### ISSUE THREAD

**Issue by Mike1977** [StjerneIdioten/I3D-Blender-Addon#150]
### Discussed in https://github.com/StjerneIdioten/I3D-Blender-Addon/discussions/149

<div type='discussions-op-text'>

<sup>Originally posted by **Mike1977** February  5, 2022</sup>
I know its not possible to import an i3D since the shapes are locked in an encryptet format. But all the settings like material, clip distance, shaders, collision mask ect, are stored in the readable portion of the i3d. It would be sooo helpful if i could just import all the settings from an i3d instead of opening the i3d in an editor and transfering all the settings into blender by hand.</div>

**Comment by StjerneIdioten** [comment]
There really wasn't a reason to open this as an issue as well, especially since I have chosen to only keep bug reports here and feature requests in the discussion forums!
