### ISSUE TITLE
mParallaxMap UV Mapping

### ISSUE THREAD

**Issue by jjdubois22** [StjerneIdioten/I3D-Blender-Addon#153]
Hello, Thank you for a really great plugin. 

I'm wondering if I'm missing something or if its not a feature of this addon. I'm using the shader editor in blender to scale my UVs for a parallax texture. works fine for albedo, specular, and normal. is there a way to do the same for the mParallaxMap (or heightmap) required for the giants shader?
![Screenshot 2022-04-18 172109](https://user-images.githubusercontent.com/62492386/163896721-17e46bbb-d988-4653-a24a-2fd3a5e54ea9.png)

**Comment by StjerneIdioten** [comment]
Is that parallax texture a new thing in FS2022? I can see you are using the building shader and I haven't had much feedback from people using the exporter to build maps and buildings, so it isn't that geared for it (out of ignorance mostly, I can't implement what I don't know about 😉)

But to answer your question, there isn't anything in the exporter at the moment that can help you with that. I will gladly implement it, if you can come up with a proposal for how you would like it to function 😄 I prefer to integrate as much with Blender as possible, but as far as I can tell from a quick search, parallax mapping is usually done with a custom node setup.

**Comment by jjdubois22** [comment]
yeah new building shader is set up for parallax occlusion. your exporter works with it just fine. but i was struggling with the scaling of textures. but i've figured out a work around. thanks for getting back to me. Much appreciated
