### ISSUE TITLE
[Bug Report] material bug

### ISSUE THREAD

**Issue by Felzow47** [StjerneIdioten/I3D-Blender-Addon#160]
## Describe the bug
A clear and concise description of what the bug is and preferably a step-by-step guide on how to reproduce it.

create a image texutre material with principaled BSDF and all default setting the export is working with no problem 

but when changing the default option of image texure from ```repeat``` to ```extend ``` the exporter work perfecly but the material is glithed 

## Log file
Please generate a logfile by checking `'Output logfile'` in the exporter and attach it to the issue.

## Blend File (*optiona*l)
**Beware that anything attached to the issue can be seen/downloaded by anyone!!!**

A .zip containing a .blend file along with any resources referred to in the .blend file, except for stuff from the $data of Farming Simulator.

In case you want your stuff to stay private you should make a minimal example, that still causes the bug and attach that instead.

## Screenshots
normal image texture with extend my BSDF have the default option
![image](https://user-images.githubusercontent.com/49567056/212898537-96b474d6-410b-40dd-8543-e4743ebbf5b9.png)
and in giant editor.....
![image](https://user-images.githubusercontent.com/49567056/212898797-5be7f6b8-00fd-44a7-8e7a-0fd5e91b24b5.png)

**Comment by ssnd292** [comment]
Whats exactly the issue here?

Without a normal map, you wont have the proper tangets calculated. This looks like user error.

**Comment by NMC-TBone** [comment]
When you use "Extend" on a image texture in blender it will extend the image by repeating pixels on its edges which is a easy way to get a fast result result in blender for use in renders etc. But this will not work outside blender and the uv map should be made probably to fit the texture you use (also set the extension back to repeat, this will show you the same result you see in Giants Editor)
![image](https://user-images.githubusercontent.com/57712777/232254020-c70642dc-8eac-4254-a00f-b3b6108a1788.png)

**Comment by StjerneIdioten** [comment]
I agree that this looks like some form of user error. Not all features of Blender textures are directly translatable into Giants Editor compatible features and especially for textures you should really only use the very basic of setups as most thing wont be converted for use in GE by the exporter.
