### ISSUE TITLE
New materials

### ISSUE THREAD

**Issue by StjerneIdioten** [StjerneIdioten/I3D-Blender-Addon#176]
### Discussed in https://github.com/StjerneIdioten/I3D-Blender-Addon/discussions/175

<div type='discussions-op-text'>

<sup>Originally posted by **JmGarciaYT** August 31, 2023</sup>
Recently I have seen that there are new materials but I have downloaded the latest version but the new materials do not come out, any way to add the new materials.</div>

**Comment by JmGarciaYT** [comment]
I already found the materials and updated it.
![image](https://github.com/StjerneIdioten/I3D-Blender-Addon/assets/51722711/74be3e87-2dda-41fd-9bfd-d1ccc1848baa)

**Comment by StjerneIdioten** [comment]
I also have the materials and renderings, but I am still looking for the names 😉

**Comment by StjerneIdioten** [comment]
> I already found the materials and updated it. 

Your own version maybe, I see no pull request for the exporter 😅 

@ssnd292

**Comment by JmGarciaYT** [comment]
> > I already found the materials and updated it.
> 
> Your own version maybe, I see no pull request for the exporter 😅
> 
> @ssnd292 did you figure out if these are indeed the names?

I was talking to him by discord and I sent him the file, but he told me that he was investigating to know the real names but at the moment he didn't know anything, that's why I put an extraction request because I wasn't sure, the same, at the moment it has worked for me.

**Comment by ssnd292** [comment]
@StjerneIdioten I am not getting a response and I doubt I will. Just add them and call them something arbitrary.

**Comment by StjerneIdioten** [comment]
> @StjerneIdioten I am not getting a response and I doubt I will. Just add them and call them something arbitrary.

I guess Unknown 1..2..3 will do 😄

**Comment by StjerneIdioten** [comment]
This has now been implemented and is in pre-release
