### ISSUE TITLE
Update i3d mappings in supplied vehicle xml files

### ISSUE THREAD

**Issue by StjerneIdioten** [StjerneIdioten/I3D-Blender-Addon#32]
**Is your feature request related to a problem? Please describe.**
It is annoying that the i3dmappings has to be set manually every time something changes in the model.

**Describe the solution you'd like**
It should be possible to supply an id for the node, which then gets used to map to a position in the node tree.

**Additional context**
```
    <i3dMappings>
        <i3dMapping id="pgII25m_main_component1" node="0>" />
```
`id` should be set inside of blender on a per node basis. The `node` field should be updated depending on its place in the scenegraph. And the xml file of the mod should be suppliable somewhere in blender as well

**Comment by kbrandwijk** [comment]
Can't `id` just be the name of the object? No need to specify it seperately.
