### ISSUE TITLE
After export UV area gets streched on weird places

### ISSUE THREAD

**Issue by ShermyPermy** [StjerneIdioten/I3D-Blender-Addon#37]
I am making a building in Blender.
Inside blender the UV and the textures on the building look great.
after export i open it up in GE and there some textures look great as in Blender but a few spots there are stretch and deformation going on in the texture.

I added my export log and a pic from blender and GE.

I hope you can fix this.
Love your version of the plugin so far.
Cant wait what else you come up with to do on the plugin.

best regards,

Herman
[Distillery Factory Main 1_export_log.txt](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/4493476/Distillery.Factory.Main.1_export_log.txt)
![Schermafdruk 2020-04-17 15 44 48](https://user-images.githubusercontent.com/9304688/79579190-91221a80-80c7-11ea-9784-7a69ea7d839d.png)
![Schermafdruk 2020-04-17 15 45 19](https://user-images.githubusercontent.com/9304688/79579192-92534780-80c7-11ea-9213-acbb6daecc43.png)

**Comment by ssnd292** [comment]
This seems to have nothing to do with exporter. It is not subdivided into squares of roughly 2x2m
Also, are you using tileable textures? Or is it a single texture for the whole building.
Stretched UVs happened when UV islands are in a different UV space.

**Comment by StjerneIdioten** [comment]
Since there is no response, I assume this was resolved by the tips from @ssnd292.
