### ISSUE TITLE
Support for user attributes

### ISSUE THREAD

**Issue by kbrandwijk** [StjerneIdioten/I3D-Blender-Addon#42]
**Is your feature request related to a problem? Please describe.**
Currently, there's no way to set user attributes on objects in Blender, they can only be set in GE

**Describe the solution you'd like**
The same ability as in GE (key, type, value).

**Describe alternatives you've considered**
None

**Additional context**
For reference:
![image](https://user-images.githubusercontent.com/852069/85146796-4307cf80-b24e-11ea-9c50-89b03ac6f760.png)

**Comment by StjerneIdioten** [comment]
![image](https://user-images.githubusercontent.com/11218511/92533195-39c94600-f232-11ea-97f3-11398b222161.png)

![image](https://user-images.githubusercontent.com/11218511/92533205-3fbf2700-f232-11ea-8c22-8153a02ad50a.png)
