### ISSUE TITLE
Support for vertex weights

### ISSUE THREAD

**Issue by kbrandwijk** [StjerneIdioten/I3D-Blender-Addon#43]
**Is your feature request related to a problem? Please describe.**
The old exporter had a checkbox 'Skin Weights', although I never actually got that to work. Either way, it would be nice to have support for exporting vertex weights.

**Describe the solution you'd like**
Include blendweights in the export file

**Describe alternatives you've considered**
x

**Additional context**
I'll add an example when I can find it again :)

**Comment by ssnd292** [comment]
Its already here https://github.com/StjerneIdioten/I3D-Blender-Addon/issues/31

**Comment by kbrandwijk** [comment]
Is that the same thing? 
![image](https://user-images.githubusercontent.com/852069/85154500-d1348380-b257-11ea-976f-0e6c39a334f1.png)

**Comment by StjerneIdioten** [comment]
To my knowledge vertex weight painting works in conjunction with armatures and bones, which is to be exported as "skinned meshes" for use in GE.
If you have some other use case for it I would need that described and also how it should be used in GE so I can figure out the proper formatting in the i3d file.
