### ISSUE TITLE
Problem with MergeGroups

### ISSUE THREAD

**Issue by crisan211** [StjerneIdioten/I3D-Blender-Addon#47]
**Describe the bug**
The plugin does not export when exporting a model with empty (transform group) using the mergegroups. Without using the mergegroup it exports without problems and if I remove the empty and put the mergegroup also exports without problems. 

**Log file**
i3dio.exporter:export_blend_to_i3d:INFO: Blender version is: 2.83.2
i3dio.exporter:export_blend_to_i3d:INFO: I3D Exporter version is: (1, 0, 0)
i3dio.exporter:export_blend_to_i3d:INFO: Exporting to C:\Users\fuent\Documents\My Games\FarmingSimulator2019\mods\Man\1.i3d
i3dio.exporter:_export_selected_objects:INFO: 'Selected Objects' export is selected'
i3dio.exporter:_add_object_to_i3d:DEBUG: [backDoor] is of type 'MESH'
i3dio.i3d.I3D:add_merge_group_node:DEBUG: [1] Adding merge group node
i3dio.i3d.I3D:add_merge_group_node:DEBUG: [1] New merge group
i3dio.node_classes.merge_group.MergeGroup:__init__:DEBUG: [MergedMesh_1] Initialized merge group
i3dio.node_classes.node.MergeGroupChild:_create_xml_element:DEBUG: [backDoor] Filling out basic attributes, {name='backDoor', nodeId='1'}
i3dio.xml_i3d:write_property_group:INFO: Writing non-default properties from propertygroup: 'I3DNodeObjectAttributes'
i3dio.xml_i3d:write_property_group:INFO: Wrote '0' properties
i3dio.xml_i3d:write_property_group:INFO: Writing non-default properties from propertygroup: 'I3DNodeShapeAttributes'
i3dio.xml_i3d:write_property_group:INFO: Wrote '0' properties
i3dio.node_classes.node.MergeGroupChild:_add_transform_to_xml_element:DEBUG: [backDoor] transforming to new transform-basis with <Matrix 4x4 (1.0000,  0.0000,  0.0000,  0.0000)
            (0.0000, -0.0000, -1.0000,  3.4021)
            (0.0000,  1.0000, -0.0000, -6.1182)
            (0.0000,  0.0000,  0.0000,  1.0000)>
i3dio.node_classes.node.MergeGroupChild:_add_transform_to_xml_element:DEBUG: [backDoor] translation is <Vector (0.0000, 3.4021, -6.1182)>
i3dio.node_classes.node.MergeGroupChild:_add_transform_to_xml_element:DEBUG: [backDoor] has translation: [7.55411e-16 3.40207 -6.11817]
i3dio.node_classes.node.MergeGroupChild:_add_transform_to_xml_element:DEBUG: [backDoor] has rotation(degrees): [90 -0 0]
i3dio.node_classes.node.MergeGroupChild:__init__:DEBUG: [backDoor] Initialized as a 'MergeGroupChild'
i3dio.exporter:_add_object_to_i3d:DEBUG: [backDoor] processing objects children
i3dio.exporter:export_blend_to_i3d:ERROR: Exception that stopped the exporter
Traceback (most recent call last):
  File "C:\Program Files (x86)\Blender\blender-2.83.2-windows64\2.83\scripts\addons\i3dio\exporter.py", line 58, in export_blend_to_i3d
    _export_selected_objects(i3d)
  File "C:\Program Files (x86)\Blender\blender-2.83.2-windows64\2.83\scripts\addons\i3dio\exporter.py", line 98, in _export_selected_objects
    _export(i3d, bpy.context.selected_objects)
  File "C:\Program Files (x86)\Blender\blender-2.83.2-windows64\2.83\scripts\addons\i3dio\exporter.py", line 105, in _export
    _add_object_to_i3d(i3d, blender_object)
  File "C:\Program Files (x86)\Blender\blender-2.83.2-windows64\2.83\scripts\addons\i3dio\exporter.py", line 150, in _add_object_to_i3d
    _add_object_to_i3d(i3d, child, node)
UnboundLocalError: local variable 'node' referenced before assignment
i3dio.exporter:export_blend_to_i3d:INFO: Export took 0.014 seconds
**Screenshots**

**Comment by StjerneIdioten** [comment]
Should be fixed now :-)

**Comment by crisan211** [comment]
Crash Blender when i export it.. Here is the log:
https://pastebin.com/0CH75tGA

**Comment by StjerneIdioten** [comment]
Crashing blender? That's a first. I can also see that it doesn't really do anything unusual in the log until it suddenly just cuts it short (Which it actually shouldn't be able to)

Does blender crash with an error message of some sort? Because I am gonna need some more information or some example files to figure this one out :-P

**Comment by crisan211** [comment]
I have reinstalled the plugin and everything works fine. Thank you very much for fixing it so quickly. If I find any more bugs I'll report it :)

**Comment by StjerneIdioten** [comment]
Ah okay. Sometimes blender can be a bit iffy with reloading, enabling/disabling addons. Since the whole system they have implemented is a bit wonky. So sometimes a full reinstall is the best option :-P 

Glad to hear that everything is working again. I appreciate that you take the time to post bugs for me to fix ;-) And that someone actually uses the addon.
