### ISSUE TITLE
Duplicate transform groups

### ISSUE THREAD

**Issue by crisan211** [StjerneIdioten/I3D-Blender-Addon#48]
**Describe the bug**
When exporting, everything inside an empty is duplicated. Everything inside the transform group moving parts and hydraulics (the yellow underline) is duplicated. Everything that is not underlined is a duplicate of the moving parts and hydraulics transform group

**Log file**
Please generate a logfile by checking `'Output logfile'` in the exporter and attach it to the issue.

**Screenshots**
![Captura](https://user-images.githubusercontent.com/68563589/87988038-ef540480-cadf-11ea-92b8-99d7ea2c5a2a.PNG)

**Comment by StjerneIdioten** [comment]
could you add the log file as well so I can see what is going on upon export?

**Comment by crisan211** [comment]
[1_export_log.txt](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/4950148/1_export_log.txt)

**Comment by crisan211** [comment]
![image](https://user-images.githubusercontent.com/68563589/87989381-39d68080-cae2-11ea-98c4-e0fb900016cf.png)
![image](https://user-images.githubusercontent.com/68563589/87989417-48bd3300-cae2-11ea-8349-7b377fe92db6.png)

This you mean?

**Comment by StjerneIdioten** [comment]
Yeah exactly, I am gonna look into it and hopefully fix it ;-)

**Comment by StjerneIdioten** [comment]
I tried playing around with it and I might have found out what is going on. I can see from your export log that you are using the "Selected Objects" mode for exporting. This mode takes all of the objects you have currently selected and exports them as top-level nodes and automatically exports all of the children as well of those objects, which would give you duplicate objects if you select everything.

![image](https://user-images.githubusercontent.com/11218511/88077880-0ea06f80-cb7c-11ea-89cf-36e2eb922fef.png)
![image](https://user-images.githubusercontent.com/11218511/88078047-40b1d180-cb7c-11ea-9140-c44be95add76.png)

Where as if I export like this:

![image](https://user-images.githubusercontent.com/11218511/88077975-2e379800-cb7c-11ea-95f4-0358230de4a5.png)
![image](https://user-images.githubusercontent.com/11218511/88078108-558e6500-cb7c-11ea-8542-41e3d84982a2.png)

It gives the expected output.

I know this is a little bit confusing perhaps, but currently the 'selected objects' export mode exports all of the objects you have selected AS WELL as their children. So if you also select the children, then you end up with this weird hierarchy.
I might change it in the future to only export the objects you have selected (and not autoexport children), but then I need to figure out what to do with selected children or grandchildren and how they should be placed in the scenegraphtree etc.

**Comment by crisan211** [comment]
Ok, then I will select the objects without their children.. Thank you for the answer and very good job you did with the plugin ;)

**Comment by StjerneIdioten** [comment]
Did it solve your problem? :-) Just so I can close the issue.

**Comment by crisan211** [comment]
Yes :)
