### ISSUE TITLE
Problem with FillVolume

### ISSUE THREAD

**Issue by crisan211** [StjerneIdioten/I3D-Blender-Addon#49]
**Describe the bug**
The game gives lua errors when there is a fillVolume exported with the plugin. I've been testing, exporting a fillVolume from the game, importing it into blender and exporting it again and it also gives error. However, I tried to export the same object from Maya and it doesn't give any problem. All this without making any changes in the object.

**Log file**
[1_export_log.txt](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/4955539/1_export_log.txt)
[log.txt](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/4955560/log.txt)

**Screenshots**

**Comment by StjerneIdioten** [comment]
I have no idea about fillVolumes and it is not something that has been tested/thought of yet :-) If you can provide me a non-binary i3d file exported from maya, with a working fillvolume. Then I would love to make it work.

**Comment by crisan211** [comment]
[1.zip](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/4955602/1.zip)

**Comment by StjerneIdioten** [comment]
The only thing I can see that is different in the i3d file of that maya export, compared with what is happening in your export log is that you don't enable any of the attributes that are exported in the maya version. That is castShadows, receiveShadows and a static rigidbody. 

Apart from that I can't really see what it should be annoyed about. I guess the important clue in your lua log is "Warning (script): Unknown entity id 0... " Which appears several times, but I don't know where that comes from. Are you able to open the exported i3d in GE?

**Comment by crisan211** [comment]
Exported from maya or blender?

**Comment by StjerneIdioten** [comment]
Blender. Because if it opens in GE, then the i3d code is working (Assuming that the GE error log is clear)

Could it be some sort of index error in your xml? Since I don't guarantee that my node indexes are gonna be the same as in maya. Or even the same from export to export (Due to it depending entirely on whatever order blender stores the objects in)

And I believe that error message has something to do with accessing nodes by index.

**Comment by crisan211** [comment]
![image](https://user-images.githubusercontent.com/68563589/88100809-5daacc80-cb9d-11ea-9519-ce15c6415de7.png)

Just have this warning:
Warning: i3d contains non-binary indexed triangle sets: C:/Users/fuent/Documents/My Games/FarmingSimulator2019/mods/Man/tipper juego.i3d

I don't see any error with the index. If you have discord, i can show you the screen and you can see for yourself

**Comment by StjerneIdioten** [comment]
I was just going off of, what the lua log you attached said. I am not much into the actual scripting side of things (At least not something that interacts directly with the i3d file) and it seems to be a problem that only presents itself in scripts.

Could you both an i3d export from maya and blender? So I can compare the files directly instead.

**Comment by crisan211** [comment]
[files.zip](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/4956075/files.zip)

**Comment by StjerneIdioten** [comment]
The only difference is firstly the naming of the nodes. "FillVolume" in the maya i3d and "1" in the blender i3d. The same goes for the shapes themselves.

The next difference is as I mentioned before, the lack of properties in the blender i3d, because I assume you haven't set them in blender.

Apart from that there is absolutely no difference.

**Comment by StjerneIdioten** [comment]
I've been conversing with some other people, and it is the case that fill volumes need a very specific name for their mesh/IndexedTriangleSet. 

This isn't actually a supported thing in the addon yet (I will add that to the backlog now that I know of it)
If you only have one fillVolume you can sort of trick the exporter to do it properly by naming your fillVolume mesh in blender to 'fillVolumeShape'

That should get you the proper export.

**Comment by StjerneIdioten** [comment]
857e8e2202ba549d24fe6ad349ed96b5340b60ad adds a checkbox for the meshes, that sets them as a fillVolume and does this name replacement that is needed for i3d to understand it.

Hopefully this helps with your issues.

**Comment by crisan211** [comment]
Now is working. You could add a button or something when exporting to change the name of the mesh to xxxxxShape as in Maya to avoid problems like this. Thank you again ;)

**Comment by StjerneIdioten** [comment]
I believe in keeping as many features in line with the native interface of blender. So I would like to keep the IndexedTriangleSet name tied to the blender mesh name. The checkmark field that I have added should be more than enough for getting around this problem for fill volumes. I only know of a few other rare cases, where the IndexedTriangleSet needs to be named something specific. I will handle that, when someone posts an issue about it ;-)
