### ISSUE TITLE
Some attributes enabled by default

### ISSUE THREAD

**Issue by crisan211** [StjerneIdioten/I3D-Blender-Addon#50]
**Is your feature request related to a problem? Please describe.**
The attributes cast Shadowmap and receive Shadomap should be enabled by default as 90% of the objects have shadows and if you have a project with many pieces and have to go one by one activating those attributes is a bit boring

**Describe the solution you'd like**
Having the cast Shadowmap and receive Shadomap attributes enabled by default

**Describe alternatives you've considered**

**Additional context**

**Comment by StjerneIdioten** [comment]
I have taken the approach that I follow what is 'default' in GE. This means that cast shadows and such are disabled per default. In the future the idea is to have templates for different default combinations of settings (#34), just as there is in the maya exporter. 
For now you just have to do the trivial stuff or remember to do it as you create the objects ;-) Fortunately the settings are saved so you only have to do it once.
