### ISSUE TITLE
Problem with vehicleShader (StaticLight)

### ISSUE THREAD

**Issue by crisan211** [StjerneIdioten/I3D-Blender-Addon#55]
**Describe the bug**
The plugin gives an error when exporting. According to the log it is a material error. The material has the specular texture and the normal map and also a shader with the VehicleShader which has StaticLight on it. From what I have been looking at, the problem is with the StaticLight, because if I change it to Colormask it exports well. 

**Log file**
[1_export_log.txt](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/5084565/1_export_log.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/68563589/90402652-0d416480-e0a0-11ea-99aa-08b78a8d3b39.png)
![image](https://user-images.githubusercontent.com/68563589/90402688-19c5bd00-e0a0-11ea-9a48-518bdaeba499.png)

**Comment by StjerneIdioten** [comment]
Judging from the error log it is an error related to the shader export code. I am not at my pc right now, but I will fix it later.

**Comment by StjerneIdioten** [comment]
The issue was a minor oversight in the code, that only presented itself when a shader used a single float value for one of its parameters (which doesn't happen that often).

**Comment by crisan211** [comment]
Now is working, thank you for the fix :)
