### ISSUE TITLE
Add textures without nodes

### ISSUE THREAD

**Issue by crisan211** [StjerneIdioten/I3D-Blender-Addon#58]
**Is your feature request related to a problem? Please describe.**
Having to use the nodes requires a little more experience in blending and for someone who has just started it can be difficult

**Describe the solution you'd like**
An option in materials where add the textures to the material without the need to resort to nodes

**Describe alternatives you've considered**

**Additional context**

**Comment by StjerneIdioten** [comment]
I am all for making it easier for people, but this is really not something that I would like to implement. Using nodes is an essential part of using blender and as this exporter seeks to bridge the gap between blender and GE. It is assumed that people know how to properly use blender first.

[This](https://www.youtube.com/watch?v=moKFSMJwpmE) video might help you in that regard and apart from that Redphoenix from Vertex Dezigns has made an excellent quick introduction to use this exporter. Which you can find [here](https://youtu.be/lRDPuKh9gow?t=325) (I've linked the exact timestamp where he talks about it)
