### ISSUE TITLE
FS Data path resolution not working with relative paths enabled

### ISSUE THREAD

**Issue by tkralicek** [StjerneIdioten/I3D-Blender-Addon#64]
If you have Relative Paths enabled in the Blender Save & Load settings then files from FS Data folder are not resolved as files relative to the FS data path during the export.

Blender setting:
![image](https://user-images.githubusercontent.com/56938178/92263964-c34ce100-eedd-11ea-936a-aeb4bc6afca1.png)

When the plugin is configured with this settings, then relative path to your scene file is returned:
![image](https://user-images.githubusercontent.com/56938178/92262480-7c5dec00-eedb-11ea-8790-0d5ab1a276ea.png)

The same happens for Shader source in material properties:
![image](https://user-images.githubusercontent.com/56938178/92264425-8503f180-eede-11ea-97f9-8ffc3e8b6a0f.png)

**Log file**
```
i3dio.utility:as_fs_relative_path:DEBUG: Original path: C:\Users\Tomas\OneDrive\..\..\..\Program Files (x86)\Steam\steamapps\common\Farming Simulator 19\data\shaders\vehicleShader.xml
i3dio.utility:as_fs_relative_path:DEBUG: fs_data_path //..\..\..\Program Files (x86)\Steam\steamapps\common\Farming Simulator 19\data\
i3dio.node_classes.file.Shader:_copy_file:INFO: [vehicleShader.xml] is not an FS builtin and will be copied
```

The export is working correctly if the Relative Paths option is disabled.

**Comment by StjerneIdioten** [comment]
Ah yes, I see that. Thanks for the very descriptive report! On my system I have the blend files and the game on separate drives, so the error didn't present itself in testing.
