### ISSUE TITLE
Normal Map node breaks export

### ISSUE THREAD

**Issue by Kieruss** [StjerneIdioten/I3D-Blender-Addon#71]
In order to get the Normal map to display properly (for Material Preview and Rendered views), I pass it through a "Normal Map" (Vector -> Normal Map) before connecting to the Normal input. Attempting to export an I3D like this causes it to fail. Bypassing the Normal Map (so the dds file goes straight into the Normal input) allows me to export again.

**Comment by ssnd292** [comment]
Cannot confirm. Can you show a picture of your setup? What exporter Version are you on?

**Comment by Kieruss** [comment]
Sorry, my bad. I'd removed the .png source file, although Blender must have cached it, since it still rendered properly. Odd that it only upset the export when passing through the Normal Map. I've now pointed it at the .dds file and the export is working properly.

Keep up the great work ;)

**Comment by ssnd292** [comment]
Just a hint: Removing it by deleting the node does not delete it from the Blender file as its still linked. To fully remove data, Go to the Blender File Tab in the Outliner, Rightclick the Data and hit Delete.
![2020-09-26 11_23_01-Blender  E__Modding_FS19_vertexdezignprojects_4 - Modding_1 - Blender_Blender_FS](https://user-images.githubusercontent.com/3914410/94337457-b312b800-ffea-11ea-8637-c3210f7c6eb8.jpg)

![2020-09-26 11_23_19-Blender_  E__Modding_FS19_vertexdezignprojects_4 - Modding_1 - Blender_Blender_F](https://user-images.githubusercontent.com/3914410/94337458-b5751200-ffea-11ea-9aec-d1aa4de490d8.jpg)

**Comment by StjerneIdioten** [comment]
There also currently exists some bugs in the blender python api itself, which causes blender to not properly update stuff between runs of the exporter (For example shader nodes that still exists although you have deleted them) I have implemented some workarounds for this previously, but it might not catch all ;-) They are working on fixing the bug though.
