### ISSUE TITLE
Geometry names change when exporting

### ISSUE THREAD

**Issue by Maaslandmods** [StjerneIdioten/I3D-Blender-Addon#75]
When exporting, sometimes my fillVolume takes over the  meshdata geometry name of the exactFillRootNodeShape they share the same material. 
In Blender 
The fillVolume has the geometry name fillVolumeShape
The exactFillRootNodeShape has the geometry name exactFillRootNodeShape

[
[HerderMRTZ550B_export_log.txt](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/5304878/HerderMRTZ550B_export_log.txt)
](url)

**Comment by Maaslandmods** [comment]
When exporting for a second time this doesn't happen.

I don't know what causes it.

**Comment by StjerneIdioten** [comment]
You can just check the export log/console for the version number. It should be printed as one of the first lines when exporting ;-) You log is saying "1.2.0-feat.1", but that shouldn't change anything for this issue.

**Comment by StjerneIdioten** [comment]
Is that export log from a successful export or one where they are "switched"? Because from the log it does export `fillVolumeShape` for the `fillVolume` object and the  `exactFillRootNodeShape` for the `exactFillRootNode` object, which I believe is correct? They both seem to have the same material, `lambert1`, which should be okay. I can see though that those two meshes have the exact same number of vertices and faces and so on.

**Comment by Maaslandmods** [comment]
Yes, it is the same object. Just duplicated and renamed. 
I had this issue twice, and now (3rd time) succeeded in replicating it.

How to replicate
Export the .blend to i3d
Save i3d as binary
Export and overwrite the i3d
[
[herderMRTZ550B_export_log.txt](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/5313972/herderMRTZ550B_export_log.txt)
](url)

**Comment by NMC-TBone** [comment]
Did some testing on this and by the looks of it thats not something related to the exporter. When the raw i3d file shapes gets converted to binary shapes file it creates instances of meshes that is the same (which I guess will save some resources). So this isn't really a issue and has nothing to say for the different shapes either. If you want the keep the shape names unique just slightly change the the mesh on one of the objects.
