### ISSUE TITLE
improved MergeGroup Selection

### ISSUE THREAD

**Issue by CCL1106** [StjerneIdioten/I3D-Blender-Addon#79]
**Is your feature request related to a problem? Please describe.**
its a kind of annoying to tip the whole merge group names again and again, if handling different groups

**Describe the solution you'd like**
dropdown list which offers the already set merge Group roots

**Comment by StjerneIdioten** [comment]
To add to that, the potential for seeing every object which is a part of a mergegroup. Maybe even the ability to select them all?
