### ISSUE TITLE
Exporter crashes, when trying to export a mesh without mesh data.

### ISSUE THREAD

**Issue by StjerneIdioten** [StjerneIdioten/I3D-Blender-Addon#82]
**Describe the bug**
If someone tries to export a mesh object that has no vertices, edges or faces, then it crashes.

**Proposed Solution**
Ignore the object (or convert it to an empty) and throw a warning in the log.

**Log file**
[untitled_export_log.txt](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/5673232/untitled_export_log.txt)

**Comment by PhiGei2000** [comment]
This seems to be fixed. 

I have tried to export an empty cube without any vertices and an empty object was exported. There was also a warning in the log file.

[untitled_export_log.txt](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/11300505/untitled_export_log.txt)

**Comment by StjerneIdioten** [comment]
I just checked the code just to be entirely sure and yes it would seem that I've fixed that at some point. Thank you for checking 👍🏻
