### ISSUE TITLE
Overhaul export selection

### ISSUE THREAD

**Issue by StjerneIdioten** [StjerneIdioten/I3D-Blender-Addon#83]
**Is your feature request related to a problem? Please describe.**
The exporter selection modes could use an overhaul. It is possible in newer versions of blender to mix and match selection of objects and collections.

**Comment by ssnd292** [comment]
I'd rather wage to leave as is. I actually like the way it is right now.

**Comment by StjerneIdioten** [comment]
And maybe that is the conclusion I end up with after taking a look at it ;-)
