### ISSUE TITLE
Alpha Color for Vertex Painting is always 1

### ISSUE THREAD

**Issue by ssnd292** [StjerneIdioten/I3D-Blender-Addon#93]
I have this setup in Blender where Red is Alpha 0 and Green is Alpha 1

![2021-01-04 13_09_51-Blender_  C__Users_ssnd2_Desktop_Temp_VertexColorTest_AlphaVertexColorTest blend](https://user-images.githubusercontent.com/3914410/103533850-26e81a80-4e8e-11eb-9af6-dba6d345e96e.jpg)

Exported, every Vertex has the Alpha of 1.

![2021-01-04 13_10_15-untitled i3d - Visual Studio Code](https://user-images.githubusercontent.com/3914410/103533881-310a1900-4e8e-11eb-94b3-17c0b41a7785.jpg)
[VertexColorTest.zip](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/5764540/VertexColorTest.zip)

Expected is that at least those painted green, should have a different alpha value.

**Comment by StjerneIdioten** [comment]
Exporter does what it is supposed to. It is just Blender having a very lackluster implementation of modifying the alpha channel. [This](https://blenderartists.org/t/how-do-you-use-the-alpha-channel-of-vertex-colors/1166252/8) discussion on blenderartist mentions how to use it.
