### ISSUE TITLE
Range parameter of lights is not transfered into i3d

### ISSUE THREAD

**Issue by ssnd292** [StjerneIdioten/I3D-Blender-Addon#94]
Create a light, define custome Range of 10.

In i3d it's still 25.

![2021-01-12 19_42_54-](https://user-images.githubusercontent.com/3914410/104358227-6c4fbc00-550e-11eb-9a6b-95dd214b7667.jpg)
![2021-01-12 19_43_12-GIANTS Editor 64bit 8 2 2 - E__Modding_FS19_FS19_1MWBGA_FS19_1MWBGA_test i3d](https://user-images.githubusercontent.com/3914410/104358229-6d80e900-550e-11eb-80c3-f5c3aaf690ee.jpg)

**Comment by StjerneIdioten** [comment]
The exporter distance parameter as range, but it is really only used in Eevee as a custom cutoff distance. So might have to change it to something else.
